<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Сравнение товаров");
$APPLICATION->SetPageProperty("title", "Сравнение товаров");?>
<?$APPLICATION->IncludeComponent(
	"aspro:catalog.compare.result.tires2", 
	"main", 
	array(
		"IBLOCK_TYPE" => "aspro_tires2_catalog",
		"IBLOCK_ID" => "0",
		"BASKET_URL" => '/basket/',
		"ACTION_VARIABLE" => $arParams["ACTION_VARIABLE"],
		"PRODUCT_ID_VARIABLE" => $arParams["PRODUCT_ID_VARIABLE"],
		"SECTION_ID_VARIABLE" => $arParams["SECTION_ID_VARIABLE"],
		"FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_PICTURE",
			2 => "DETAIL_PICTURE",
		),
		"PROPERTY_CODE" => array(
			0 => "PROIZVODITEL",
			1 => "CML2_ARTICLE",
			2 => "SEZONNOST",
			3 => "SHIPY",
			4 => "HIT",
			5 => "SHIRINA_PROFILYA",
			6 => "VYSOTA_PROFILYA",
			7 => "POSADOCHNYY_DIAMETR",
			8 => "SHIRINA_DISKA",
			9 => "POSADOCHNYY_DIAMETR_DISKA",
			10 => "COUNT_OTVERSTIY",
			11 => "MEZHBOLTOVOE_RASSTOYANIE",
			12 => "EMKOST",
			13 => "POLARNOST",
			14 => "KLEMMY",
			15 => "VISCOSITY",
			16 => "OIL_TYPE",
			17 => "ENGINE_TYPE",
			18 => "VOLUME",
			19 => "THREAD_LENGTH",
			20 => "DIAMETER",
		),
		"NAME" => $arParams["COMPARE_NAME"],
		"SHOW_MEASURE" => $arParams["SHOW_MEASURE"],
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "86400",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"SKU_DETAIL_ID" => $arParams["SKU_DETAIL_ID"],
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => $arParams["SHOW_PRICE_COUNT"],
		"PRICE_VAT_INCLUDE" => "N",
		"PRICE_VAT_SHOW_VALUE" => $arParams["PRICE_VAT_SHOW_VALUE"],
		"DISPLAY_ELEMENT_SELECT_BOX" => "N",
		"ELEMENT_SORT_FIELD_BOX" => $arParams["ELEMENT_SORT_FIELD_BOX"],
		"ELEMENT_SORT_ORDER_BOX" => $arParams["ELEMENT_SORT_ORDER_BOX"],
		"ELEMENT_SORT_FIELD_BOX2" => $arParams["ELEMENT_SORT_FIELD_BOX2"],
		"ELEMENT_SORT_ORDER_BOX2" => $arParams["ELEMENT_SORT_ORDER_BOX2"],
		"ELEMENT_SORT_FIELD" => $arParams["COMPARE_ELEMENT_SORT_FIELD"],
		"ELEMENT_SORT_ORDER" => $arParams["COMPARE_ELEMENT_SORT_ORDER"],
		"DETAIL_URL" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["element"],
		"OFFERS_FIELD_CODE" => $arParams["COMPARE_OFFERS_FIELD_CODE"],
		"OFFERS_PROPERTY_CODE" => $arParams["COMPARE_OFFERS_PROPERTY_CODE"],
		"OFFERS_CART_PROPERTIES" => $arParams["OFFERS_CART_PROPERTIES"],
		"CONVERT_CURRENCY" => "N",
		"CURRENCY_ID" => $arParams["CURRENCY_ID"],
		"HIDE_NOT_AVAILABLE" => "N",
		"TEMPLATE_THEME" => (isset($arParams["TEMPLATE_THEME"])?$arParams["TEMPLATE_THEME"]:""),
		"COMPONENT_TEMPLATE" => "main",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO"
	),
	$component
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>